package com.example.xiaozhu.Bean;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;

import com.example.xiaozhu.Model.DB.Mydbhelper;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Created by xiaozhu on 2016/7/28.
 */
public class CityRsc {
    public Map<Integer,String> province;
    public Map<String,List<String>> municiple;
    private Context mContext;
    private Mydbhelper mydbhelper;
    public CityRsc(Context mContext){
        this.mContext = mContext;
        mydbhelper = new Mydbhelper(mContext,"City.db",null,1);
        insert();
        initProvince();
        initMuniciple();
    }
    public void insert(){
        SQLiteDatabase database = mydbhelper.getWritableDatabase();
        Cursor cursor = database.query("swf_area",null,null,null,null,null,null);
        if(cursor.getCount() == 0) {
            database.execSQL("INSERT INTO swf_area VALUES ('100', '0', '热门城市', '0')");
            database.execSQL("INSERT INTO swf_area VALUES ('101', '100', '北京', '0')");
            database.execSQL("INSERT INTO swf_area VALUES ('102', '100', '上海', '0')");
            database.execSQL("INSERT INTO swf_area VALUES ('103', '100', '香港', '0')");
            database.execSQL("INSERT INTO swf_area VALUES ('104', '100', '澳门', '0')");
            database.execSQL("INSERT INTO swf_area VALUES ('105', '100', '台湾', '0')");
            database.execSQL("INSERT INTO swf_area VALUES ('106', '100', '重庆', '0')");
            database.execSQL("INSERT INTO swf_area VALUES ('107', '100', '天津', '0')");
            database.execSQL("INSERT INTO swf_area VALUES ('200', '0', '安徽', '1')");
            database.execSQL("INSERT INTO swf_area VALUES ('201', '200', '合肥', '1')");
            database.execSQL("INSERT INTO swf_area VALUES ('202', '200', '安庆', '1')");
            database.execSQL("INSERT INTO swf_area VALUES ('203', '200', '毫州', '1')");
            database.execSQL("INSERT INTO swf_area VALUES ('204', '200', '蚌埠', '1')");
            database.execSQL("INSERT INTO swf_area VALUES ('205', '200', '滁州', '1')");
            database.execSQL("INSERT INTO swf_area VALUES ('206', '200', '巢湖', '1')");
            database.execSQL("INSERT INTO swf_area VALUES ('207', '200', '池州', '1')");
            database.execSQL("INSERT INTO swf_area VALUES ('208', '200', '阜阳', '1')");
            database.execSQL("INSERT INTO swf_area VALUES ('209', '200', '淮北', '1')");
            database.execSQL("INSERT INTO swf_area VALUES ('210', '200', '淮南', '1')");
            database.execSQL("INSERT INTO swf_area VALUES ('211', '200', '黄山站', '1')");
            database.execSQL("INSERT INTO swf_area VALUES ('212', '200', '六安', '1')");
            database.execSQL("INSERT INTO swf_area VALUES ('213', '200', '马鞍山', '1')");
            database.execSQL("INSERT INTO swf_area VALUES ('214', '200', '宿州', '1')");
            database.execSQL("INSERT INTO swf_area VALUES ('215', '200', '铜陵', '1')");
            database.execSQL("INSERT INTO swf_area VALUES ('216', '200', '芜湖', '1')");
            database.execSQL("INSERT INTO swf_area VALUES ('217', '200', '宣城', '1')");
            database.execSQL("INSERT INTO swf_area VALUES ('600', '0', '福建', '5')");
            database.execSQL("INSERT INTO swf_area VALUES ('601', '600', '福州', '5')");
            database.execSQL("INSERT INTO swf_area VALUES ('602', '600', '龙岩', '5')");
            database.execSQL("INSERT INTO swf_area VALUES ('603', '600', '南平', '5')");
            database.execSQL("INSERT INTO swf_area VALUES ('604', '600', '宁德', '5')");
            database.execSQL("INSERT INTO swf_area VALUES ('605', '600', '莆田', '5')");
            database.execSQL("INSERT INTO swf_area VALUES ('606', '600', '泉州', '5')");
            database.execSQL("INSERT INTO swf_area VALUES ('607', '600', '三明', '5')");
            database.execSQL("INSERT INTO swf_area VALUES ('608', '600', '厦门', '5')");
            database.execSQL("INSERT INTO swf_area VALUES ('609', '600', '漳州', '5')");
            database.execSQL("INSERT INTO swf_area VALUES ('700', '0', '甘肃', '6')");
            database.execSQL("INSERT INTO swf_area VALUES ('701', '700', '兰州', '6')");
            database.execSQL("INSERT INTO swf_area VALUES ('702', '700', '白银', '6')");
            database.execSQL("INSERT INTO swf_area VALUES ('703', '700', '定西', '6')");
            database.execSQL("INSERT INTO swf_area VALUES ('704', '700', '合作', '6')");
            database.execSQL("INSERT INTO swf_area VALUES ('705', '700', '金昌', '6')");
            database.execSQL("INSERT INTO swf_area VALUES ('706', '700', '酒泉', '6')");
            database.execSQL("INSERT INTO swf_area VALUES ('707', '700', '嘉峪关', '6')");
            database.execSQL("INSERT INTO swf_area VALUES ('708', '700', '临夏', '6')");
            database.execSQL("INSERT INTO swf_area VALUES ('709', '700', '平凉', '6')");
            database.execSQL("INSERT INTO swf_area VALUES ('710', '700', '庆阳', '6')");
            database.execSQL("INSERT INTO swf_area VALUES ('711', '700', '天水', '6')");
            database.execSQL("INSERT INTO swf_area VALUES ('712', '700', '武威', '6')");
            database.execSQL("INSERT INTO swf_area VALUES ('713', '700', '武都', '6')");
            database.execSQL("INSERT INTO swf_area VALUES ('714', '700', '张掖', '6')");
            database.execSQL("INSERT INTO swf_area VALUES ('800', '0', '广东', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('801', '800', '广州', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('802', '800', '潮州', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('803', '800', '东莞', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('804', '800', '佛山', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('805', '800', '河源', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('806', '800', '惠州', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('807', '800', '江门', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('808', '800', '揭阳', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('809', '800', '梅州', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('810', '800', '茂名', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('811', '800', '清远', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('812', '800', '深圳', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('813', '800', '汕头', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('814', '800', '韶关', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('815', '800', '汕尾', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('816', '800', '阳江', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('817', '800', '云浮', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('818', '800', '珠海', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('819', '800', '中山', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('820', '800', '湛江', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('821', '800', '肇庆', '7')");
            database.execSQL("INSERT INTO swf_area VALUES ('900', '0', '广西', '8')");
            database.execSQL("INSERT INTO swf_area VALUES ('901', '900', '南宁', '8')");
            database.execSQL("INSERT INTO swf_area VALUES ('902', '900', '北海', '8')");
            database.execSQL("INSERT INTO swf_area VALUES ('903', '900', '白色', '8')");
            database.execSQL("INSERT INTO swf_area VALUES ('904', '900', '崇左', '8')");
            database.execSQL("INSERT INTO swf_area VALUES ('905', '900', '防城港', '8')");
            database.execSQL("INSERT INTO swf_area VALUES ('906', '900', '桂林', '8')");
            database.execSQL("INSERT INTO swf_area VALUES ('907', '900', '贵港', '8')");
            database.execSQL("INSERT INTO swf_area VALUES ('908', '900', '贺州', '8')");
            database.execSQL("INSERT INTO swf_area VALUES ('909', '900', '河池', '8')");
            database.execSQL("INSERT INTO swf_area VALUES ('910', '900', '柳州', '8')");
            database.execSQL("INSERT INTO swf_area VALUES ('911', '900', '来宾', '8')");
            database.execSQL("INSERT INTO swf_area VALUES ('912', '900', '钦州', '8')");
            database.execSQL("INSERT INTO swf_area VALUES ('913', '900', '梧州', '8')");
            database.execSQL("INSERT INTO swf_area VALUES ('914', '900', '玉林', '8')");
            database.execSQL("INSERT INTO swf_area VALUES ('1000', '0', '贵州', '9')");
            database.execSQL("INSERT INTO swf_area VALUES ('1001', '1000', '贵阳', '9')");
            database.execSQL("INSERT INTO swf_area VALUES ('1002', '1000', '安顺', '9')");
            database.execSQL("INSERT INTO swf_area VALUES ('1003', '1000', '毕节', '9')");
            database.execSQL("INSERT INTO swf_area VALUES ('1004', '1000', '都匀', '9')");
            database.execSQL("INSERT INTO swf_area VALUES ('1005', '1000', '凯里', '9')");
            database.execSQL("INSERT INTO swf_area VALUES ('1006', '1000', '六盘水', '9')");
            database.execSQL("INSERT INTO swf_area VALUES ('1007', '1000', '晴隆', '9')");
            database.execSQL("INSERT INTO swf_area VALUES ('1008', '1000', '铜仁', '9')");
            database.execSQL("INSERT INTO swf_area VALUES ('1009', '1000', '兴义', '9')");
            database.execSQL("INSERT INTO swf_area VALUES ('1010', '1000', '遵义', '9')");
            database.execSQL("INSERT INTO swf_area VALUES ('1100', '0', '海南', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1101', '1100', '海口', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1102', '1100', '白沙', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1103', '1100', '保亭', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1104', '1100', '澄迈', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1105', '1100', '昌江', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1106', '1100', '儋州', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1107', '1100', '定安', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1108', '1100', '东方', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1109', '1100', '临高', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1110', '1100', '陵水', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1111', '1100', '乐东', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1112', '1100', '南沙岛', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1113', '1100', '琼海', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1114', '1100', '琼中', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1115', '1100', '三亚', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1116', '1100', '屯昌', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1117', '1100', '五指山', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1118', '1100', '文昌', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1119', '1100', '万宁', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1120', '1100', '西沙', '10')");
            database.execSQL("INSERT INTO swf_area VALUES ('1200', '0', '河北', '11')");
            database.execSQL("INSERT INTO swf_area VALUES ('1201', '1200', '石家庄', '11')");
            database.execSQL("INSERT INTO swf_area VALUES ('1202', '1200', '保定', '11')");
            database.execSQL("INSERT INTO swf_area VALUES ('1203', '1200', '承德', '11')");
            database.execSQL("INSERT INTO swf_area VALUES ('1204', '1200', '沧州', '11')");
            database.execSQL("INSERT INTO swf_area VALUES ('1205', '1200', '衡水', '11')");
            database.execSQL("INSERT INTO swf_area VALUES ('1206', '1200', '邯郸', '11')");
            database.execSQL("INSERT INTO swf_area VALUES ('1207', '1200', '廊坊', '11')");
            database.execSQL("INSERT INTO swf_area VALUES ('1208', '1200', '秦皇岛', '11')");
            database.execSQL("INSERT INTO swf_area VALUES ('1209', '1200', '唐山', '11')");
            database.execSQL("INSERT INTO swf_area VALUES ('1210', '1200', '邢台', '11')");
            database.execSQL("INSERT INTO swf_area VALUES ('1211', '1200', '张家口', '11')");
            database.execSQL("INSERT INTO swf_area VALUES ('1300', '0', '河南', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1301', '1300', '郑州', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1302', '1300', '安阳', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1303', '1300', '鹤壁', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1304', '1300', '焦作', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1305', '1300', '济源', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1306', '1300', '开封', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1307', '1300', '洛阳', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1308', '1300', '漯河', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1309', '1300', '南阳', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1310', '1300', '濮阳', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1311', '1300', '平顶山', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1312', '1300', '三门峡', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1313', '1300', '商丘', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1314', '1300', '新乡', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1315', '1300', '许昌', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1316', '1300', '信阳', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1317', '1300', '周口', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1318', '1300', '驻马店', '12')");
            database.execSQL("INSERT INTO swf_area VALUES ('1400', '0', '黑龙江', '13')");
            database.execSQL("INSERT INTO swf_area VALUES ('1401', '1400', '哈尔滨', '13')");
            database.execSQL("INSERT INTO swf_area VALUES ('1402', '1400', '大庆', '13')");
            database.execSQL("INSERT INTO swf_area VALUES ('1403', '1400', '大兴安岭', '13')");
            database.execSQL("INSERT INTO swf_area VALUES ('1404', '1400', '鹤岗', '13')");
            database.execSQL("INSERT INTO swf_area VALUES ('1405', '1400', '黑河', '13')");
            database.execSQL("INSERT INTO swf_area VALUES ('1406', '1400', '佳木斯', '13')");
            database.execSQL("INSERT INTO swf_area VALUES ('1407', '1400', '鸡西', '13')");
            database.execSQL("INSERT INTO swf_area VALUES ('1408', '1400', '牡丹江', '13')");
            database.execSQL("INSERT INTO swf_area VALUES ('1409', '1400', '齐齐哈尔', '13')");
            database.execSQL("INSERT INTO swf_area VALUES ('1410', '1400', '七台河', '13')");
            database.execSQL("INSERT INTO swf_area VALUES ('1411', '1400', '双鸭山', '13')");
            database.execSQL("INSERT INTO swf_area VALUES ('1412', '1400', '绥化', '13')");
            database.execSQL("INSERT INTO swf_area VALUES ('1413', '1400', '伊春', '13')");
            database.execSQL("INSERT INTO swf_area VALUES ('1500', '0', '湖北', '14')");
            database.execSQL("INSERT INTO swf_area VALUES ('1501', '1500', '武汉', '14')");
            database.execSQL("INSERT INTO swf_area VALUES ('1502', '1500', '鄂州', '14')");
            database.execSQL("INSERT INTO swf_area VALUES ('1503', '1500', '恩施', '14')");
            database.execSQL("INSERT INTO swf_area VALUES ('1504', '1500', '黄石', '14')");
            database.execSQL("INSERT INTO swf_area VALUES ('1505', '1500', '黄冈', '14')");
            database.execSQL("INSERT INTO swf_area VALUES ('1506', '1500', '荆州', '14')");
            database.execSQL("INSERT INTO swf_area VALUES ('1507', '1500', '荆门', '14')");
            database.execSQL("INSERT INTO swf_area VALUES ('1508', '1500', '潜江', '14')");
            database.execSQL("INSERT INTO swf_area VALUES ('1509', '1500', '十堰', '14')");
            database.execSQL("INSERT INTO swf_area VALUES ('1510', '1500', '随州', '14')");
            database.execSQL("INSERT INTO swf_area VALUES ('1511', '1500', '神农架', '14')");
            database.execSQL("INSERT INTO swf_area VALUES ('1512', '1500', '天门', '14')");
            database.execSQL("INSERT INTO swf_area VALUES ('1513', '1500', '襄阳', '14')");
            database.execSQL("INSERT INTO swf_area VALUES ('1514', '1500', '孝感', '14')");
            database.execSQL("INSERT INTO swf_area VALUES ('1515', '1500', '咸宁', '14')");
            database.execSQL("INSERT INTO swf_area VALUES ('1516', '1500', '仙桃', '14')");
            database.execSQL("INSERT INTO swf_area VALUES ('1517', '1500', '宜昌', '14')");
            database.execSQL("INSERT INTO swf_area VALUES ('1600', '0', '湖南', '15')");
            database.execSQL("INSERT INTO swf_area VALUES ('1601', '1600', '长沙', '15')");
            database.execSQL("INSERT INTO swf_area VALUES ('1602', '1600', '常德', '15')");
            database.execSQL("INSERT INTO swf_area VALUES ('1603', '1600', '郴州', '15')");
            database.execSQL("INSERT INTO swf_area VALUES ('1604', '1600', '衡阳', '15')");
            database.execSQL("INSERT INTO swf_area VALUES ('1605', '1600', '怀化', '15')");
            database.execSQL("INSERT INTO swf_area VALUES ('1606', '1600', '吉首', '15')");
            database.execSQL("INSERT INTO swf_area VALUES ('1607', '1600', '娄底', '15')");
            database.execSQL("INSERT INTO swf_area VALUES ('1608', '1600', '黔阳', '15')");
            database.execSQL("INSERT INTO swf_area VALUES ('1609', '1600', '邵阳', '15')");
            database.execSQL("INSERT INTO swf_area VALUES ('1610', '1600', '湘潭', '15')");
            database.execSQL("INSERT INTO swf_area VALUES ('1611', '1600', '岳阳', '15')");
            database.execSQL("INSERT INTO swf_area VALUES ('1612', '1600', '益阳', '15')");
            database.execSQL("INSERT INTO swf_area VALUES ('1613', '1600', '永州', '15')");
            database.execSQL("INSERT INTO swf_area VALUES ('1614', '1600', '株洲', '15')");
            database.execSQL("INSERT INTO swf_area VALUES ('1615', '1600', '张家界', '15')");
            database.execSQL("INSERT INTO swf_area VALUES ('1700', '0', '吉林', '16')");
            database.execSQL("INSERT INTO swf_area VALUES ('1701', '1700', '长春', '16')");
            database.execSQL("INSERT INTO swf_area VALUES ('1702', '1700', '白山', '16')");
            database.execSQL("INSERT INTO swf_area VALUES ('1703', '1700', '白城', '16')");
            database.execSQL("INSERT INTO swf_area VALUES ('1704', '1700', '吉林', '16')");
            database.execSQL("INSERT INTO swf_area VALUES ('1705', '1700', '辽源', '16')");
            database.execSQL("INSERT INTO swf_area VALUES ('1706', '1700', '四平', '16')");
            database.execSQL("INSERT INTO swf_area VALUES ('1707', '1700', '松原', '16')");
            database.execSQL("INSERT INTO swf_area VALUES ('1708', '1700', '通化', '16')");
            database.execSQL("INSERT INTO swf_area VALUES ('1709', '1700', '延吉', '16')");
            database.execSQL("INSERT INTO swf_area VALUES ('1800', '0', '江苏', '17')");
            database.execSQL("INSERT INTO swf_area VALUES ('1801', '1800', '南京', '17')");
            database.execSQL("INSERT INTO swf_area VALUES ('1802', '1800', '常州', '17')");
            database.execSQL("INSERT INTO swf_area VALUES ('1803', '1800', '淮安', '17')");
            database.execSQL("INSERT INTO swf_area VALUES ('1804', '1800', '连云港', '17')");
            database.execSQL("INSERT INTO swf_area VALUES ('1805', '1800', '南通', '17')");
            database.execSQL("INSERT INTO swf_area VALUES ('1806', '1800', '苏州', '17')");
            database.execSQL("INSERT INTO swf_area VALUES ('1807', '1800', '宿迁', '17')");
            database.execSQL("INSERT INTO swf_area VALUES ('1808', '1800', '秦州', '17')");
            database.execSQL("INSERT INTO swf_area VALUES ('1809', '1800', '无锡', '17')");
            database.execSQL("INSERT INTO swf_area VALUES ('1810', '1800', '徐州', '17')");
            database.execSQL("INSERT INTO swf_area VALUES ('1811', '1800', '盐城', '17')");
            database.execSQL("INSERT INTO swf_area VALUES ('1812', '1800', '扬州', '17')");
            database.execSQL("INSERT INTO swf_area VALUES ('1813', '1800', '镇江', '17')");
            database.execSQL("INSERT INTO swf_area VALUES ('1900', '0', '江西', '18')");
            database.execSQL("INSERT INTO swf_area VALUES ('1901', '1900', '南昌', '18')");
            database.execSQL("INSERT INTO swf_area VALUES ('1902', '1900', '抚州', '18')");
            database.execSQL("INSERT INTO swf_area VALUES ('1903', '1900', '赣州', '18')");
            database.execSQL("INSERT INTO swf_area VALUES ('1904', '1900', '九江', '18')");
            database.execSQL("INSERT INTO swf_area VALUES ('1905', '1900', '景德镇', '18')");
            database.execSQL("INSERT INTO swf_area VALUES ('1906', '1900', '吉安', '18')");
            database.execSQL("INSERT INTO swf_area VALUES ('1907', '1900', '萍乡', '18')");
            database.execSQL("INSERT INTO swf_area VALUES ('1908', '1900', '上饶', '18')");
            database.execSQL("INSERT INTO swf_area VALUES ('1909', '1900', '新余', '18')");
            database.execSQL("INSERT INTO swf_area VALUES ('1910', '1900', '鹰潭', '18')");
            database.execSQL("INSERT INTO swf_area VALUES ('1911', '1900', '宜春', '18')");
            database.execSQL("INSERT INTO swf_area VALUES ('2000', '0', '辽宁', '19')");
            database.execSQL("INSERT INTO swf_area VALUES ('2001', '2000', '沈阳', '19')");
            database.execSQL("INSERT INTO swf_area VALUES ('2002', '2000', '鞍山', '19')");
            database.execSQL("INSERT INTO swf_area VALUES ('2003', '2000', '本溪', '19')");
            database.execSQL("INSERT INTO swf_area VALUES ('2004', '2000', '朝阳', '19')");
            database.execSQL("INSERT INTO swf_area VALUES ('2005', '2000', '大连', '19')");
            database.execSQL("INSERT INTO swf_area VALUES ('2006', '2000', '丹东', '19')");
            database.execSQL("INSERT INTO swf_area VALUES ('2007', '2000', '抚顺', '19')");
            database.execSQL("INSERT INTO swf_area VALUES ('2008', '2000', '阜新', '19')");
            database.execSQL("INSERT INTO swf_area VALUES ('2009', '2000', '葫芦岛', '19')");
            database.execSQL("INSERT INTO swf_area VALUES ('2010', '2000', '锦州', '19')");
            database.execSQL("INSERT INTO swf_area VALUES ('2011', '2000', '辽阳', '19')");
            database.execSQL("INSERT INTO swf_area VALUES ('2012', '2000', '盘锦', '19')");
            database.execSQL("INSERT INTO swf_area VALUES ('2013', '2000', '铁岭', '19')");
            database.execSQL("INSERT INTO swf_area VALUES ('2014', '2000', '营口', '19')");
            database.execSQL("INSERT INTO swf_area VALUES ('2100', '0', '内蒙古', '20')");
            database.execSQL("INSERT INTO swf_area VALUES ('2101', '2100', '呼和浩特', '20')");
            database.execSQL("INSERT INTO swf_area VALUES ('2102', '2100', '阿拉善左旗', '20')");
            database.execSQL("INSERT INTO swf_area VALUES ('2103', '2100', '包头', '20')");
            database.execSQL("INSERT INTO swf_area VALUES ('2104', '2100', '赤峰', '20')");
            database.execSQL("INSERT INTO swf_area VALUES ('2105', '2100', '鄂尔多斯', '20')");
            database.execSQL("INSERT INTO swf_area VALUES ('2106', '2100', '呼伦贝尔', '20')");
            database.execSQL("INSERT INTO swf_area VALUES ('2107', '2100', '集宁', '20')");
            database.execSQL("INSERT INTO swf_area VALUES ('2108', '2100', '临河', '20')");
            database.execSQL("INSERT INTO swf_area VALUES ('2109', '2100', '通辽', '20')");
            database.execSQL("INSERT INTO swf_area VALUES ('2110', '2100', '乌兰浩特', '20')");
            database.execSQL("INSERT INTO swf_area VALUES ('2111', '2100', '乌海', '20')");
            database.execSQL("INSERT INTO swf_area VALUES ('2112', '2100', '锡林浩特', '20')");
            database.execSQL("INSERT INTO swf_area VALUES ('2200', '0', '宁夏', '21')");
            database.execSQL("INSERT INTO swf_area VALUES ('2201', '2200', '银川', '21')");
            database.execSQL("INSERT INTO swf_area VALUES ('2202', '2200', '固原', '21')");
            database.execSQL("INSERT INTO swf_area VALUES ('2203', '2200', '石嘴山', '21')");
            database.execSQL("INSERT INTO swf_area VALUES ('2204', '2200', '吴忠', '21')");
            database.execSQL("INSERT INTO swf_area VALUES ('2205', '2200', '中卫', '21')");
            database.execSQL("INSERT INTO swf_area VALUES ('2300', '0', '青海', '22')");
            database.execSQL("INSERT INTO swf_area VALUES ('2301', '2300', '西宁', '22')");
            database.execSQL("INSERT INTO swf_area VALUES ('2302', '2300', '果洛', '22')");
            database.execSQL("INSERT INTO swf_area VALUES ('2303', '2300', '海东', '22')");
            database.execSQL("INSERT INTO swf_area VALUES ('2304', '2300', '海南', '22')");
            database.execSQL("INSERT INTO swf_area VALUES ('2305', '2300', '海北', '22')");
            database.execSQL("INSERT INTO swf_area VALUES ('2306', '2300', '海西', '22')");
            database.execSQL("INSERT INTO swf_area VALUES ('2307', '2300', '黄南', '22')");
            database.execSQL("INSERT INTO swf_area VALUES ('2308', '2300', '玉树', '22')");
            database.execSQL("INSERT INTO swf_area VALUES ('2400', '0', '山东', '23')");
            database.execSQL("INSERT INTO swf_area VALUES ('2401', '2400', '济南', '23')");
            database.execSQL("INSERT INTO swf_area VALUES ('2402', '2400', '滨州', '23')");
            database.execSQL("INSERT INTO swf_area VALUES ('2403', '2400', '东营', '23')");
            database.execSQL("INSERT INTO swf_area VALUES ('2404', '2400', '德州', '23')");
            database.execSQL("INSERT INTO swf_area VALUES ('2405', '2400', '菏泽', '23')");
            database.execSQL("INSERT INTO swf_area VALUES ('2406', '2400', '济宁', '23')");
            database.execSQL("INSERT INTO swf_area VALUES ('2407', '2400', '莱芜', '23')");
            database.execSQL("INSERT INTO swf_area VALUES ('2408', '2400', '临沂', '23')");
            database.execSQL("INSERT INTO swf_area VALUES ('2409', '2400', '聊城', '23')");
            database.execSQL("INSERT INTO swf_area VALUES ('2410', '2400', '青岛', '23')");
            database.execSQL("INSERT INTO swf_area VALUES ('2411', '2400', '日照', '23')");
            database.execSQL("INSERT INTO swf_area VALUES ('2412', '2400', '泰安', '23')");
            database.execSQL("INSERT INTO swf_area VALUES ('2413', '2400', '潍坊', '23')");
            database.execSQL("INSERT INTO swf_area VALUES ('2414', '2400', '威海', '23')");
            database.execSQL("INSERT INTO swf_area VALUES ('2415', '2400', '烟台', '23')");
            database.execSQL("INSERT INTO swf_area VALUES ('2416', '2400', '淄博', '23')");
            database.execSQL("INSERT INTO swf_area VALUES ('2417', '2400', '枣庄', '23')");
            database.execSQL("INSERT INTO swf_area VALUES ('2500', '0', '山西', '24')");
            database.execSQL("INSERT INTO swf_area VALUES ('2501', '2500', '太原', '24')");
            database.execSQL("INSERT INTO swf_area VALUES ('2502', '2500', '长治', '24')");
            database.execSQL("INSERT INTO swf_area VALUES ('2503', '2500', '大同', '24')");
            database.execSQL("INSERT INTO swf_area VALUES ('2504', '2500', '晋城', '24')");
            database.execSQL("INSERT INTO swf_area VALUES ('2505', '2500', '晋中', '24')");
            database.execSQL("INSERT INTO swf_area VALUES ('2506', '2500', '临汾', '24')");
            database.execSQL("INSERT INTO swf_area VALUES ('2507', '2500', '吕梁', '24')");
            database.execSQL("INSERT INTO swf_area VALUES ('2508', '2500', '朔州', '24')");
            database.execSQL("INSERT INTO swf_area VALUES ('2509', '2500', '忻州', '24')");
            database.execSQL("INSERT INTO swf_area VALUES ('2510', '2500', '阳泉', '24')");
            database.execSQL("INSERT INTO swf_area VALUES ('2511', '2500', '运城', '24')");
            database.execSQL("INSERT INTO swf_area VALUES ('2600', '0', '陕西', '25')");
            database.execSQL("INSERT INTO swf_area VALUES ('2601', '2600', '西安', '25')");
            database.execSQL("INSERT INTO swf_area VALUES ('2602', '2600', '宝康', '25')");
            database.execSQL("INSERT INTO swf_area VALUES ('2603', '2600', '宝鸡', '25')");
            database.execSQL("INSERT INTO swf_area VALUES ('2604', '2600', '陈仓', '25')");
            database.execSQL("INSERT INTO swf_area VALUES ('2605', '2600', '汉中', '25')");
            database.execSQL("INSERT INTO swf_area VALUES ('2606', '2600', '商洛', '25')");
            database.execSQL("INSERT INTO swf_area VALUES ('2607', '2600', '铜川', '25')");
            database.execSQL("INSERT INTO swf_area VALUES ('2608', '2600', '渭南', '25')");
            database.execSQL("INSERT INTO swf_area VALUES ('2609', '2600', '咸阳', '25')");
            database.execSQL("INSERT INTO swf_area VALUES ('2610', '2600', '延安', '25')");
            database.execSQL("INSERT INTO swf_area VALUES ('2611', '2600', '榆林', '25')");
            database.execSQL("INSERT INTO swf_area VALUES ('2800', '0', '四川', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2801', '2800', '成都', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2802', '2800', '阿贝', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2803', '2800', '巴中', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2804', '2800', '德阳', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2805', '2800', '达州', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2806', '2800', '广元', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2807', '2800', '广安', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2808', '2800', '甘孜', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2809', '2800', '泸州', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2810', '2800', '乐山', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2811', '2800', '凉山', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2812', '2800', '绵阳', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2813', '2800', '眉山', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2814', '2800', '内江', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2815', '2800', '南充', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2816', '2800', '攀枝花', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2817', '2800', '遂宁', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2818', '2800', '宜宾', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2819', '2800', '雅安', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2820', '2800', '自贡', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('2821', '2800', '资阳', '27')");
            database.execSQL("INSERT INTO swf_area VALUES ('3100', '0', '西藏', '30')");
            database.execSQL("INSERT INTO swf_area VALUES ('3101', '3100', '拉萨', '30')");
            database.execSQL("INSERT INTO swf_area VALUES ('3102', '3100', '阿里', '30')");
            database.execSQL("INSERT INTO swf_area VALUES ('3103', '3100', '昌都', '30')");
            database.execSQL("INSERT INTO swf_area VALUES ('3104', '3100', '林芝', '30')");
            database.execSQL("INSERT INTO swf_area VALUES ('3105', '3100', '那曲', '30')");
            database.execSQL("INSERT INTO swf_area VALUES ('3106', '3100', '日喀则', '30')");
            database.execSQL("INSERT INTO swf_area VALUES ('3107', '3100', '山南', '30')");
            database.execSQL("INSERT INTO swf_area VALUES ('3300', '0', '新疆', '32')");
            database.execSQL("INSERT INTO swf_area VALUES ('3301', '3300', '乌鲁木齐', '32')");
            database.execSQL("INSERT INTO swf_area VALUES ('3302', '3300', '阿克苏', '32')");
            database.execSQL("INSERT INTO swf_area VALUES ('3303', '3300', '阿图什', '32')");
            database.execSQL("INSERT INTO swf_area VALUES ('3304', '3300', '阿勒泰', '32')");
            database.execSQL("INSERT INTO swf_area VALUES ('3305', '3300', '阿拉尔', '32')");
            database.execSQL("INSERT INTO swf_area VALUES ('3306', '3300', '博乐', '32')");
            database.execSQL("INSERT INTO swf_area VALUES ('3307', '3300', '昌吉', '32')");
            database.execSQL("INSERT INTO swf_area VALUES ('3308', '3300', '哈密', '32')");
            database.execSQL("INSERT INTO swf_area VALUES ('3309', '3300', '和田', '32')");
            database.execSQL("INSERT INTO swf_area VALUES ('3310', '3300', '克拉玛依', '32')");
            database.execSQL("INSERT INTO swf_area VALUES ('3311', '3300', '喀什', '32')");
            database.execSQL("INSERT INTO swf_area VALUES ('3312', '3300', '库尔勒', '32')");
            database.execSQL("INSERT INTO swf_area VALUES ('3313', '3300', '石河子', '32')");
            database.execSQL("INSERT INTO swf_area VALUES ('3314', '3300', '吐鲁番', '32')");
            database.execSQL("INSERT INTO swf_area VALUES ('3315', '3300', '塔城', '32')");
            database.execSQL("INSERT INTO swf_area VALUES ('3316', '3300', '伊宁', '32')");
            database.execSQL("INSERT INTO swf_area VALUES ('3400', '0', '云南', '33')");
            database.execSQL("INSERT INTO swf_area VALUES ('3401', '3400', '昆明', '33')");
            database.execSQL("INSERT INTO swf_area VALUES ('3402', '3400', '保山', '33')");
            database.execSQL("INSERT INTO swf_area VALUES ('3403', '3400', '楚雄', '33')");
            database.execSQL("INSERT INTO swf_area VALUES ('3404', '3400', '大理', '33')");
            database.execSQL("INSERT INTO swf_area VALUES ('3405', '3400', '德宏', '33')");
            database.execSQL("INSERT INTO swf_area VALUES ('3406', '3400', '红河', '33')");
            database.execSQL("INSERT INTO swf_area VALUES ('3407', '3400', '景洪', '33')");
            database.execSQL("INSERT INTO swf_area VALUES ('3408', '3400', '丽江', '33')");
            database.execSQL("INSERT INTO swf_area VALUES ('3409', '3400', '临沧', '33')");
            database.execSQL("INSERT INTO swf_area VALUES ('3410', '3400', '怒江', '33')");
            database.execSQL("INSERT INTO swf_area VALUES ('3411', '3400', '曲靖', '33')");
            database.execSQL("INSERT INTO swf_area VALUES ('3412', '3400', '思茅', '33')");
            database.execSQL("INSERT INTO swf_area VALUES ('3413', '3400', '文山', '33')");
            database.execSQL("INSERT INTO swf_area VALUES ('3414', '3400', '香格里拉', '33')");
            database.execSQL("INSERT INTO swf_area VALUES ('3415', '3400', '玉溪', '33')");
            database.execSQL("INSERT INTO swf_area VALUES ('3416', '3400', '昭通', '33')");
            database.execSQL("INSERT INTO swf_area VALUES ('3500', '0', '浙江', '34')");
            database.execSQL("INSERT INTO swf_area VALUES ('3501', '3500', '杭州', '34')");
            database.execSQL("INSERT INTO swf_area VALUES ('3502', '3500', '湖州', '34')");
            database.execSQL("INSERT INTO swf_area VALUES ('3503', '3500', '嘉兴', '34')");
            database.execSQL("INSERT INTO swf_area VALUES ('3504', '3500', '金华', '34')");
            database.execSQL("INSERT INTO swf_area VALUES ('3505', '3500', '丽水', '34')");
            database.execSQL("INSERT INTO swf_area VALUES ('3506', '3500', '宁波', '34')");
            database.execSQL("INSERT INTO swf_area VALUES ('3507', '3500', '衢州', '34')");
            database.execSQL("INSERT INTO swf_area VALUES ('3508', '3500', '绍兴', '34')");
            database.execSQL("INSERT INTO swf_area VALUES ('3509', '3500', '台州', '34')");
            database.execSQL("INSERT INTO swf_area VALUES ('3510', '3500', '温州', '34')");
            database.execSQL("INSERT INTO swf_area VALUES ('3511', '3500', '舟山', '34')");
        }
    }
    public void initProvince(){
        province = new LinkedHashMap<>();
        SQLiteDatabase database = mydbhelper.getWritableDatabase();
        Cursor cursor = database.query("swf_area",null,null,null,null,null,null);
        if(cursor.moveToFirst()){
            do {
                if(cursor.getInt(cursor.getColumnIndex("id"))%100==0){
                    province.put(cursor.getInt(cursor.getColumnIndex("id")),cursor.getString(cursor.getColumnIndex("name")));
                }
            }while (cursor.moveToNext());
        }
        cursor.close();
    }
    public void initMuniciple(){
        municiple = new LinkedHashMap<>();
        SQLiteDatabase database = mydbhelper.getWritableDatabase();
        Cursor cursor = database.query("swf_area",null,null,null,null,null,null);
        for(Map.Entry<Integer,String> entry : province.entrySet()){
            int proid = entry.getKey();
            String pronm = entry.getValue();
            List<String> list = new ArrayList<>();
            if(cursor.moveToFirst()){
                do {
                    if(cursor.getInt(cursor.getColumnIndex("parent_id"))==proid){
                        list.add(cursor.getString(cursor.getColumnIndex("name")));
                    }
                }while (cursor.moveToNext());
            }
            municiple.put(pronm,list);
        }
        cursor.close();
    }
}
